[project]
name = "breaking-bad-rag"
version = "0.2.1"
description = "RAG (Retrieval-Augmented Generation) implementation using Breaking Bad plots as Knowledge Base."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.5",
    "gradio>=6.20.0",
    "ollama>=0.6.2",
    "pandas>=3.0.5",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "sqlmodel>=0.0.39",
]
